### ISSUE TITLE
インストール方法についてご教示ください

### ISSUE THREAD

**Issue by nightquestibanez** [nohararc/discord_voiceroid#10]
お世話になっております。

ディスコードのテキストをボイスロイドに喋らせたくてこちらを拝見し、行き詰まってしまいました。

やったこと
1.
「discord_voiceroid-master.zip」をDドライブに解凍。

2.
discordのbotを作成しtokenを取得後、利用したいサーバーに招待する
→招待済み（オフラインになっている）

3.
private_sample.pyをリネームし「private.py」
中身を以下に編集
----------------------------
token = abcd123456
voice_channel_id = 123456789
----------------------------

4.
「ffmpeg-n4.4-latest-win64-gpl-shared-4.4」を「C:\Program Files\ffmpeg」内に格納。

5.
上記binフォルダを環境変数に登録。

6.
コマンドプロンプトで「ffmpeg」を打つといっぱい文字が出て認識している様子。

7.
「python-3.10.2-embed-win32」をインストール。

8.
必要なライブラリをインストール
コマンドプロンプト以下を打つと認識していない。
pip install git+https://github.com/Nkyoku/pyvcroid2.git

表示されるメッセージは
----------------------------
C:\Users\USERX>pip install git+https://github.com/Nkyoku/pyvcroid2.git
'pip' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
----------------------------

この様になってしまいます。
無知な質問で大変申し訳ございません。

ぜひこの機能を使いたいのでどうかご教示お願いいたします。

**Comment by nohararc** [comment]
@nightquestibanez `表示されるメッセージ`にもありますとおり、pipへのPATHが通っていないようです。ffmpegと同様にpipへのPATHを通して再度お試しください。

**Comment by nightquestibanez** [comment]
ご確認ありがとうございます！
何度も大変申し訳ございません。

環境変数でPATHを通してみました。
Scripts ディレクトリも通しました。

正常に設定されたか確認するため以下のコマンドを打って通っているのを確認しました。
```
C:\Users\USERX>python -V
Python 3.10.2

C:\Users\USERX>pip -V
pip 21.2.4 from C:\python\lib\site-packages\pip (python 3.10)
```
そしてコマンドプロンプトで「pip install git+https://github.com/Nkyoku/pyvcroid2.git」を打ったところ以下のメッセージが出てしまいました。

```
C:\Users\USERX>pip install git+https://github.com/Nkyoku/pyvcroid2.git
Collecting git+https://github.com/Nkyoku/pyvcroid2.git
  Cloning https://github.com/Nkyoku/pyvcroid2.git to c:\users\userx\appdata\local\temp\pip-req-build-czm05ze6
  ERROR: Error [WinError 2] 指定されたファイルが見つかりません。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```
「discord_voiceroid-master.zip」この中身を全然別のところに解凍しているのですが、それも間違えていますでしょうか。

恐れ入りますがご教示お願い致します。

**Comment by nohararc** [comment]
gitをインストール、PATH通して再度お試しください
