### ISSUE TITLE
Discord.py

### ISSUE THREAD

**Issue by kuroneko6423** [nohararc/discord_voiceroid#7]
Discord.pyのバージョンを教えてください。

**Comment by kuroneko6423** [comment]
2.0.0a3267+gd30fea5bだとわからないので...

**Comment by nohararc** [comment]
@kuroneko6423 すみません今手元に環境がなくてすぐ確認できないのですが当時の最新版で動いたのは覚えています。

discord.pyの最新版(masterブランチ)では動作しないでしょうか？

ご存知かもしれませんがdiscord.pyは開発終了を宣言しているのでこのリポジトリもいずれアーカイブします。

**Comment by kuroneko6423** [comment]
最新版でやってみたんですがエラーが出て動かなかったんですよね

**Comment by kuroneko6423** [comment]
エラー内容

C:\Users\KuronekoServer\Desktop\discord_voiceroid-master>python main.py
Traceback (most recent call last):
  File "C:\Users\KuronekoServer\Desktop\discord_voiceroid-master\main.py", line 5, in <module>
    from bot import VoiceroidTTSBot
  File "C:\Users\KuronekoServer\Desktop\discord_voiceroid-master\bot.py", line 1, in <module>
    from ui import SelectTextChannel, SelectVoiceChannel
  File "C:\Users\KuronekoServer\Desktop\discord_voiceroid-master\ui.py", line 7, in <module>
    class TextChannelButton(discord.ui.Button["SelectTextChannel"]):
AttributeError: module 'discord' has no attribute 'ui'

**Comment by kuroneko6423** [comment]
ちなみにdiscord.pyが終了してるのは知っております。
discord.pyの代わりのpycordという存在もご存じです()

**Comment by nohararc** [comment]
ちらっとdiscord.pyのmaster覗いたらuiモジュール入ってそうでしたけど、頂いたエラー見た感じだと入ってないんですね🤔

**Comment by kuroneko6423** [comment]
一応pip list

C:\Users\KuronekoServer\Desktop\discord_voiceroid-master>pip list
Package            Version
------------------ -----------
aiohttp            3.7.4.post0
aiosignal          1.2.0
async-timeout      3.0.1
attrs              21.2.0
cffi               1.15.0
chardet            4.0.0
charset-normalizer 2.0.9
discord.py         1.7.3
frozenlist         1.2.0
gitdb              4.0.9
GitPython          3.1.24
idna               3.2
multidict          5.1.0
pip                20.2.3
pycparser          2.20
PyNaCl             1.4.0
pyvcroid2          0.21
setuptools         49.2.1
six                1.16.0
smmap              5.0.0
typing-extensions  3.10.0.0
yarl               1.6.3
WARNING: You are using pip version 20.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\users\kuronekoserver\appdata\local\programs\python\python39-32\python.exe -m pip install --upgrade pip' command.

**Comment by nohararc** [comment]
このリポジトリのREADMEに記載のコマンド`pip install git+https://github.com/Rapptz/discord.py.git`でdiscord.py入れました？
2系を利用するにはPyPIからではなく、masterブランチからinstallする必要があるかと思います。

**Comment by kuroneko6423** [comment]
エラーがそれでまして

C:\Users\KuronekoServer\Desktop\discord_voiceroid-master>pip install git+https://github.com/Rapptz/discord.py.git

Collecting git+https://github.com/Rapptz/discord.py.git
  Cloning https://github.com/Rapptz/discord.py.git to c:\users\kuronekoserver\appdata\local\temp\pip-req-build-vtpja004
  ERROR: Error [WinError 2] 指定されたファイルが見つかりません。 while executing command git clone -q https://github.com/Rapptz/discord.py.git 'C:\Users\KuronekoServer\AppData\Local\Temp\pip-req-build-vtpja004'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
WARNING: You are using pip version 20.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\users\kuronekoserver\appdata\local\programs\python\python39-32\python.exe -m pip install --upgrade pip' command.

**Comment by nohararc** [comment]
> `ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?`
gitをインストールした上で再度お試しください。

**Comment by kuroneko6423** [comment]
了解です

**Comment by kuroneko6423** [comment]
動きました！ありがとうございます！
