### ISSUE TITLE
接続チャンネル設定のGUIで25チャンネルほどしか表示されない問題

### ISSUE THREAD

**Issue by mono0218** [nohararc/discord_voiceroid#9]

**Comment by mono0218** [comment]
突然の質問失礼します。
接続チャンネル設定で一定のチャンネルしか表示できません。
ui.pyを見る限りtext_channels: List[discord.TextChannel]と書かれているため上から
25チャンネルが表示されているのだと思います。25チャンネル以上の表示はできないのでしょうか。
それとチャンネルをconfig上から指定して読み上げをさせることはできるのでしょうか。返信よろしくお願いいたします。

**Comment by nohararc** [comment]
>25チャンネル以上の表示はできないのでしょうか

こちら側では特に指定していないのでわかりません。気になるようでしたらdiscordpyの実装追ってみてください。


>チャンネルをconfig上から指定して読み上げをさせることはできるのでしょうか

昔のバージョンはそういう動作にしていた気がします！
https://github.com/nohararc/discord_voiceroid/blob/d703109deebe060d2c0b60ccd3646839d526609e/bot.py このへんとかどうでしょうか。

**Comment by mono0218** [comment]
ご返信ありがとうございます。
無事解決しました。ありがとうございました。
